### ISSUE TITLE
No providers - help me please

### ISSUE THREAD

**Issue by shadowdevnotreal** [blackhatethicalhacking/ScopeHunter#3]
─[parrot@parrot]─[~/Downloads/ScopeHunter]
└──╼ $./ScopeHunter.sh

 +-++-++-++-++-++-+ +-++-++-++-++-+
 |B||H||E||H||'||s| |W||O||R||L||D|
 +-++-++-++-++-++-+ +-++-++-++-++-+

Offensive security tip: The supreme art of war is to subdue the enemy without fighting. - Sun Tzu
MEANS, IT'S ☕ 1337 ⚡ TIME, 369 ☯ 
 ____                       _   _             _
/ ___|  ___ ___  _ __   ___| | | |_   _ _ __ | |_ ___ _ __
\___ \ / __/ _ \| '_ \ / _ \ |_| | | | | '_ \| __/ _ \ '__|
 ___) | (_| (_) | |_) |  __/  _  | |_| | | | | ||  __/ |
|____/ \___\___/| .__/ \___|_| |_|\__,_|_| |_|\__\___|_|
                |_|

[YOUR ARE USING ScopeHunter.sh] - (v1.0) CODED BY Chris 'SaintDruG' Abou-Chabké WITH ❤ FOR blackhatethicalhacking.com for Educational Purposes only!
CHECKING IF YOU ARE CONNECTED TO THE INTERNET!
++++ CONNECTION FOUND, LET'S GO!
Available Providers:
Enter target company name: 
paypal
Do you want to search again? (yes/no) 
yes
./ScopeHunter.sh: line 62: main_menu: command not found
./ScopeHunter.sh: line 66: syntax error near unexpected token `}'
./ScopeHunter.sh: line 66: `}'
┌─[✗]─[parrot@parrot]─[~/Downloads/ScopeHunter]
└──╼ $

**Comment by blackhatethicalhacking** [comment]
Thanks, just fixed it, you can try again
